### ISSUE TITLE
Enhance `How to use it` documentation

### ISSUE THREAD

**Issue by dearrudam** [soujava/pom-editor-maven-plugin#18]
## Description

The plugin offers a commit/rollback feature in order to offer flexibility to the users to confirm or revert any changes during executions of add-dep goa. It's needed to enhance the documentation to provide a usage recommendation about this process

## The usage recommendation

When you perform the goal `add-dep` with the command below:

```bash
$ mvn pom-editor:add-dep -Dgav='junit:junit:4.13'
```
The plugin will create a backup POM file based on the target POM if such one doesn't exist.

```bash
$ tree .
.
├── pom.xml
└── pom.xml.backup
``` 
You could perform multiple times the `add-dep` goal as you need. 

Then, when you're done, if there's no problem with the changed POM, you could confirm the changes by performing the `commit` goal. 

```bash
$ mvn pom-editor:commit
```
This goal will delete the backup POM file.
```bash
$ tree .
.
└── pom.xml
``` 

Otherwise, you could perform the `rollback` goal:
```bash
$ mvn pom-editor:rollback
```
This goal will revert the changes, replacing the changed POM file to the backup POM file;

## Acceptance Criteria

The section `How to use it` in README.adoc file must be update to include a new section explaining this usage recommendation;

**Comment by GianDeManincor** [comment]
I will work on it.
