### ISSUE TITLE
Enhance contributing file with git commit details

### ISSUE THREAD

**Issue by dearrudam** [soujava/pom-editor-maven-plugin#19]
## Description

In order to help contributors to make git commits consistent and easy to understand it's essential to have clear instructions on how to do it in the CONTRIBUTING.adoc file. Adopting the Conventional Commits Specification (https://www.conventionalcommits.org/en/v1.0.0/) it's a good way to solve this problem. 

## Proposal Solution

Add a section into the CONTRIBUTING.adoc file that explains the Conventional Commits specification and how to use it in the project. Instructions like how to format the commit messages and which types of messages to use for different changes should be included in the documentation.

## Acceptance Criteria

The CONTRIBUTING.adoc file must include:
- The new section explains the Conventional Commits specification and how to use it in the project;
- The new section with instructions on how to format commits and which types of messages to use for different types of changes;

**Comment by luiguip** [comment]
Can I be assigned? I will work on it.

**Comment by dearrudam** [comment]
Sure!! I'll be amazing to receive your contributions @luiguip !!!
