### ISSUE TITLE
Update to Java 17

### ISSUE THREAD

**Issue by otaviojava** [soujava/pom-editor-maven-plugin#2]
We currently use Java version 11 for our project, but Java 17 is the latest LTS version; we would like to update it to take advantage of its new features and performance improvements.

Updating to Java 17 will require changes to our build process and potentially some code changes. However, the benefits of upgrading will be worth the effort.

We should also ensure that our project dependencies are compatible with Java 17 before switching.

## Benefits:

* Improved performance and security
* Access to new features and functionality
* Staying up to date with the latest technology

**Comment by dearrudam** [comment]
@otaviojava, I have a question: once we do up to date this plugin to Java 17 as you're recommending, this plugin cannot be used with maven projects that it's using previous Java versions, am I right? 

It would be not a good idea maybe, because according to [JRebel Developer Report 2022](https://www.jrebel.com/resources/java-developer-productivity-report-2022), companies with over 100 employees are using Java 8 yet, while in companies with under 100 employees are increasing the utilization of Java 11 version and above. 

What do you think about it?

**Comment by midhatdrops** [comment]
Hello ! Giving my contribution to the discussion. Surely Java 17 will be a new pattern between the companies but will take some time until all migrations are done. Many companies use Java 11 (other still are in Java 8 with their legacy apps). But i think we need to embrace those versions in this project.

One suggestion/doubt: Could the "java17 mode" be a flag like "--java17" in the CLI ? At least until most of the companies/users migrate to this version.

**Comment by dearrudam** [comment]
@midhatdrops, thanks for your contribution!!!  
 
> One suggestion/doubt: Could the "java17 mode" be a flag like "--java17" in the CLI ? At least until most of the companies/users migrate to this version.

IMHO, that suggestion would work if it's a CLI application, but it's not. It is a maven plugin then it depends on the Java version used by the maven execution.

I think that we could be improving the CI process to make sure that this plugin is ready to build with newer Java versions like @otaviojava has proposed.

**Comment by brunobaiano** [comment]
Hello! My opinion is that to spread the plugin use, it should be compatible with the last LTS version.
New projects, teaching classes are some examples that will not be using older JDKs.

**Comment by dearrudam** [comment]
@brunobaiano thanks so much for your opinion!

Yeah! Today, the plugin is built with Java 11... in theory, it should work properly with the latest LTS Java version, that is Java 17. 

With that, we'll be free to produce new projects, teach classes, live coding, blog posts, and/or other content using the plugin with the latest LTS Java versions;

I think that we could add new CI runners in order to make sure that the plugin could be compiled with the latest LTS Java versions, at this time, Java 17.

**Comment by viniciusbrg** [comment]
I think it's a great idea to at least ensure that things work as expected with Java 17.

![image](https://user-images.githubusercontent.com/25652392/228708533-dba1c754-5c0f-4b2d-813d-cab14debbc67.png)

We already have a workflow defined for java 11, so we just need to create a new one with java 17, correct?

Also, we can keep this new workflow running with the same triggers as the java 11 version (for changes in the main branch & pull requests)

What do you guys think?

**Comment by dearrudam** [comment]
@viniciusbrg, that's my idea too!

Well, I think we got some options:

- Create a new GitHub Action for Java 17 
   - **Pros:** we'll separate the CI processes for each Java LTS version; 
   - **Cons**: more files to maintain;

- Rename the current one `java-11.yml` to something like `ci.yml` for example and make the build job use a matrix strategy with Java LTS versions, it looks like below:
  ```yml
  jobs:
    build:
      strategy:
        matrix:
          java: [ 11, 17 ] /# we will just need to put the next new LTS version here
  ```
     - **Pros:** less files to maintain;
     - **Cons:** more complexity to handle with;

Friends, what do you think?

**Comment by otaviojava** [comment]
I like two different files; we need to handle two files, but if this increases the CI experience, that is the goal.

**Comment by midhatdrops** [comment]
Two different files seem better, have more complexity to deal, but you'll have more granularity for each jdk version. For example, if you use some SAST tool or something like that, it does not have compatibility yet to newers LTS versions.

**Comment by viniciusbrg** [comment]
I also like this approach with two different files. Can I work on an implementation for this? 

The matrix strategy that Maximilliam suggested would be good if we had many different versions to build, but since that's not the case here, I think two files will work just fine for us.

**Comment by dearrudam** [comment]
Friends, I think that we got the point! I'll create another issue for that task:

- [ ] Create a new GitHub Action for Java 17

@otaviojava, do you think that we could close this issue when the new related issue gets closed or we could close it by now?

**Comment by otaviojava** [comment]
sure
