### ISSUE TITLE
Unnecessary GPG signing executions 

### ISSUE THREAD

**Issue by dearrudam** [soujava/pom-editor-maven-plugin#4]
Currently, the GPG maven plugin is declared into the default profile and it's been triggered by default whenever the maven `verify` lifecycle is executed.

In order to avoid this unnecessary execution when we're not trying to deploy the artifacts to Maven Central, it's needed to keep this plugin declaration in the specific profile called "release" only.

## Benefits:
- Save build time by avoiding the GPG signing process without necessity; 
- Better utilization of the maven profiles of the project in order to get a good separation of concerns;

**Comment by viniciusbrg** [comment]
Hello!

I've looked at the code, and I've noticed that the GPG plugin is declared both on the build step and at the "release" profile.

So, the solution is removing the declaration at the build step and keeping it only on the release profile.
