### ISSUE TITLE
Missing the Code of Conduct

### ISSUE THREAD

**Issue by dearrudam** [soujava/pom-editor-maven-plugin#5]
It's necessary to add the Code of Conduct for this project.

I think that we could use as an example the [Horusec's Code of Conduct](https://github.com/ZupIT/horusec/blob/main/CODE_OF_CONDUCT.md)

**Comment by dearrudam** [comment]
@otaviojava is this example good enough or do you have another example that we could use?

**Comment by otaviojava** [comment]
@dearrudam yes, this one is really good.
